name: Update screenshots

on:
    workflow_dispatch:

jobs:
    update-screenshots:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download artifact
              id: download-artifact
              uses: dawidd6/action-download-artifact@v6
              with:
                  # Optional, workflow file name or ID
                  # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
                  workflow: playwright.yml
                  # Optional, will get head commit SHA
                  pr: ${{github.event.pull_request.number}}
                  branch: main
                  name: artifact
                  name_is_regexp: true
                  if_no_artifact_found: fail
            - name: Replace files
              run: rsync -av artifact/screenshots ./ && ls -al && pwd
            - name: Commit and push screenshots
              run: |
                  git config --global user.email "jmalcans@evolution.com"
                  git config --global user.name "Janis Malcans"
                  git add ./screenshots/*
                  git commit -m "Update screenshots"
                  git push
