name: Update screenshots

on:
    workflow_dispatch:

jobs:
    update-screenshots:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Download artifact
              id: download-artifact
              uses: dawidd6/action-download-artifact@v5
              with:
                  # Optional, workflow file name or ID
                  # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
                  workflow: playwright.yml
                  # Optional, will use the specified branch. Defaults to all branches
                  branch: main
                  # Optional, defaults to all types
                  event: push
                  name: artifact
                  # Optional, name is treated as a regular expression if set true
                  name_is_regexp: true
                  # Optional, a directory where to extract artifact(s), defaults to the current directory
                  path: ./
                  # Optional, defaults to current repo
                  repo: ${{ github.repository }}
                  # Optional, check the workflow run to whether it has an artifact
                  # then will get the last available artifact from the previous workflow
                  # default false, just try to download from the last one
                  check_artifacts: false
                  # Optional, search for the last workflow run whose stored an artifact named as in `name` input
                  # default false
                  search_artifacts: false
                  # Optional, choose to skip unpacking the downloaded artifact(s)
                  # default false
                  skip_unpack: false
                  # Optional, choose how to exit the action if no artifact is found
                  # can be one of:
                  #  "fail", "warn", "ignore"
                  # default fail
                  if_no_artifact_found: fail
            - name: Replace files
              run: rsync -av artifact/screenshots ./ && ls -al && pwd
            - name: Commit and push screenshots
              run: |
                  git config --global user.email "jmalcans@evolution.com"
                  git config --global user.name "Janis Malcans"
                  git add ./screenshots/*
                  git commit -m "Update screenshots"
                  git push
